#!/usr/bin/env node
// Encode the Inter Latin subset woff2 as a base64 data URI and write it to
// src/embedded-fonts.ts so the README SVG can embed the font inline. Run again
// whenever the source font changes:
//
//   node scripts/encode-fonts.mjs

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const FONT_PATH = join(ROOT, "assets", "fonts", "Inter-latin.woff2");
const OUTPUT = join(ROOT, "src", "embedded-fonts.ts");

const data = readFileSync(FONT_PATH);
const base64 = data.toString("base64");

const banner = `// Generated by scripts/encode-fonts.mjs — DO NOT EDIT BY HAND.\n// Source font: assets/fonts/Inter-latin.woff2 (Inter, Latin subset, OFL).\n// Re-run the script after replacing the source.\n`;

const body = `export const INTER_LATIN_WOFF2_DATA_URI = "data:font/woff2;base64,${base64}";\n`;

writeFileSync(OUTPUT, `${banner}\n${body}`);
console.log(`Wrote ${OUTPUT} (${data.byteLength} byte font → ${base64.length} chars base64)`);
